robot_cameras:
  floor_robot_camera:
    active: false
    type: rgb

  ceiling_robot_camera:
    active: false
    type: rgbd

static_sensors:
  conveyor_breakbeam:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.36, 3.5, 0.88]
      rpy: [0, 0, pi]

  # kts1_camera:
  #   type: advanced_logical_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [-1.3, -5.8, 1.8]
  #     rpy: [pi, pi/2, pi/2]
  
  # kts2_camera:
  #   type: advanced_logical_camera
  #   visualize_fov: true
  #   pose:
  #     xyz: [-1.3, 5.8, 1.8]
  #     rpy: [pi, pi/2, -pi/2]

  rgb_camera_kts1:
      type: rgb_camera
      visualize_fov: true
      pose:
        xyz: [-1.3, -5.8, 1.8]
        rpy: [pi, pi/2, pi/2]

  rgb_camera_kts2:
      type: rgb_camera
      visualize_fov: true
      pose:
        xyz: [-1.3, 5.8, 1.8]
        rpy: [pi, pi/2, -pi/2]

  rgb_left_bins:
      type: rgb_camera
      visualize_fov: true
      pose:
        xyz: [-2.275, -3.0, 1.8]
        rpy: [pi, pi/2, 0]

  rgb_right_bins:
      type: rgb_camera
      visualize_fov: true
      pose:
        xyz: [-2.275, 3.0, 1.8]
        rpy: [pi, pi/2, 0]                

  ceiling_conveyor_camera:
    type: rgb_camera
    visualize_fov: true
    pose:
      xyz: [-0.6, 3.63, 1.35]
      rpy: [0, 1.57, 0]   